[project]
name = "RigetZoo"
version = "0.1.0"
description = "RigetZoo OccSpec"
requires-python = ">=3.10"

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"
